#!/usr/bin/env python
"""Milvus Lite smoke test for hybrid financial retrieval.

Schema intent:
- dense: searched dense vector for text/image/table textual representation
- sparse: searched BM25 sparse vector generated by Milvus from content
- modality: scalar filter for text/image/table
- content: returned searchable text representation
- raw_ref: returned original reference, such as Markdown table or image path
- company/year: scalar filters
"""

from __future__ import annotations

import hashlib
import math
import shutil
import sys
from pathlib import Path
from typing import Any

try:
    from pymilvus import (
        AnnSearchRequest,
        DataType,
        Function,
        FunctionType,
        MilvusClient,
        RRFRanker,
    )
except ImportError:
    print(
        "pymilvus is not installed. Install V2 requirements first:\n"
        "  /root/miniconda3/bin/python -m pip install -r V2/requirements.txt"
    )
    sys.exit(1)


ROOT_DIR = Path(__file__).resolve().parent
DB_PATH = ROOT_DIR / "milvus_lite_smoke.db"
COLLECTION_NAME = "financial_report_v2_milvus_smoke"

DENSE_FIELD = "dense"
SPARSE_FIELD = "sparse"
OUTPUT_FIELDS = ["doc_id", "content", "raw_ref", "modality", "company", "year"]
EMBED_DIM = 96

COMPANIES = ["宁德时代", "比亚迪", "贵州茅台", "腾讯控股", "隆基绿能"]

FEATURE_GROUPS = {
    "研发": ["研发", "技术", "专利", "创新", "实验室", "算法", "平台"],
    "新能源": ["新能源", "动力电池", "储能", "光伏", "组件", "硅片", "电动车", "碳酸锂"],
    "现金流": ["现金流", "经营活动", "现金", "回款", "应收", "资本开支", "现金等价物"],
    "营收": ["营收", "收入", "销售", "订单", "增长", "同比", "市场份额"],
    "毛利率": ["毛利率", "毛利", "成本", "原材料", "价格", "产品结构"],
    "风险": ["风险", "竞争", "政策", "汇率", "供应链", "减值", "价格波动"],
    "国际化": ["海外", "国际", "出口", "全球", "欧洲", "东南亚"],
    "渠道": ["渠道", "经销商", "客户", "门店", "直销", "会员"],
}

DOCS = [
    {
        "company": "宁德时代",
        "year": "2024",
        "modality": "text",
        "content": "宁德时代2024年持续加大研发投入，重点推进麒麟电池、钠离子电池和储能系统技术。公司新增多项动力电池专利，研发团队围绕安全性、能量密度和快充体验开展验证。",
        "raw_ref": "reports/2024/宁德时代/annual-report.md#fake-report-01",
    },
    {
        "company": "宁德时代",
        "year": "2024",
        "modality": "table",
        "content": "宁德时代经营活动现金流保持净流入，客户回款节奏改善，应收账款周转效率提升。公司控制资本开支节奏，同时保障储能和新能源电池产线扩产资金。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 经营活动现金流 | 净流入 |\n| 回款 | 节奏改善 |",
    },
    {
        "company": "宁德时代",
        "year": "2024",
        "modality": "table",
        "content": "宁德时代毛利率受碳酸锂价格回落和产品结构优化影响有所修复。动力电池规模效应增强，海外客户占比提升也改善了单位制造成本。",
        "raw_ref": "| 指标 | 变化原因 |\n| --- | --- |\n| 毛利率 | 碳酸锂价格回落、产品结构优化 |",
    },
    {
        "company": "宁德时代",
        "year": "2024",
        "modality": "image",
        "content": "宁德时代提示新能源补贴政策变化、原材料价格波动和海外贸易壁垒可能影响盈利。公司通过长期采购协议和全球化产能布局降低供应链风险。",
        "raw_ref": "reports/2024/宁德时代/fake-report-04-risk-map.png",
    },
    {
        "company": "比亚迪",
        "year": "2024",
        "modality": "text",
        "content": "比亚迪研发投入集中在刀片电池、智能驾驶平台和混动系统升级。公司加强新能源汽车核心零部件自研能力，以提升整车续航、安全和成本控制。",
        "raw_ref": "reports/2024/比亚迪/annual-report.md#fake-report-05",
    },
    {
        "company": "比亚迪",
        "year": "2024",
        "modality": "table",
        "content": "比亚迪新能源汽车销量增长带动营收提升，乘用车出口和高端品牌车型贡献增量。公司在国内市场保持领先，同时加快欧洲和东南亚销售网络建设。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 新能源汽车销量 | 增长 |\n| 乘用车出口 | 贡献增量 |",
    },
    {
        "company": "比亚迪",
        "year": "2024",
        "modality": "table",
        "content": "比亚迪经营活动现金流受整车销量增长和供应链议价能力支撑。公司存货管理改善，电池和汽车业务回款稳定，现金等价物余额保持充足。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 经营活动现金流 | 受销量增长支撑 |\n| 现金等价物 | 充足 |",
    },
    {
        "company": "比亚迪",
        "year": "2024",
        "modality": "image",
        "content": "比亚迪面临新能源汽车价格竞争、海外认证周期和汇率波动风险。管理层强调通过垂直整合和规模化制造对冲行业降价压力。",
        "raw_ref": "reports/2024/比亚迪/fake-report-08-risk-map.png",
    },
    {
        "company": "贵州茅台",
        "year": "2024",
        "modality": "table",
        "content": "贵州茅台2024年酒类销售收入稳健增长，核心单品茅台酒保持供需紧平衡。直营渠道和数字化平台提升了终端触达能力。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 酒类销售收入 | 稳健增长 |\n| 直营渠道 | 终端触达提升 |",
    },
    {
        "company": "贵州茅台",
        "year": "2024",
        "modality": "table",
        "content": "贵州茅台毛利率维持高位，产品结构以高端白酒为主，吨酒价格稳定。公司通过精细化生产和渠道管理保持盈利质量。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 毛利率 | 维持高位 |\n| 产品结构 | 高端白酒为主 |",
    },
    {
        "company": "贵州茅台",
        "year": "2024",
        "modality": "table",
        "content": "贵州茅台经营活动现金流充沛，预收款和合同负债体现经销商打款积极。公司分红能力较强，现金储备覆盖生产扩建和渠道投入。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 经营活动现金流 | 充沛 |\n| 合同负债 | 经销商打款积极 |",
    },
    {
        "company": "贵州茅台",
        "year": "2024",
        "modality": "image",
        "content": "贵州茅台关注白酒消费场景变化、渠道库存波动和价格预期管理风险。公司通过稳定投放节奏和强化品牌建设维护长期需求。",
        "raw_ref": "reports/2024/贵州茅台/fake-report-12-risk-map.png",
    },
    {
        "company": "腾讯控股",
        "year": "2024",
        "modality": "text",
        "content": "腾讯控股持续投入AI大模型、云计算和安全技术研发。公司将算法能力用于广告推荐、企业服务和游戏内容生产，提升平台效率。",
        "raw_ref": "reports/2024/腾讯控股/annual-report.md#fake-report-13",
    },
    {
        "company": "腾讯控股",
        "year": "2024",
        "modality": "table",
        "content": "腾讯控股收入来自增值服务、网络广告、金融科技和企业服务。视频号广告加载率提升，小游戏生态和云业务恢复增长。",
        "raw_ref": "| 业务 | 收入表现 |\n| --- | --- |\n| 网络广告 | 视频号加载率提升 |\n| 云业务 | 恢复增长 |",
    },
    {
        "company": "腾讯控股",
        "year": "2024",
        "modality": "table",
        "content": "腾讯控股自由现金流保持稳健，经营活动现金流覆盖服务器投入、内容采购和股东回报。公司控制低效项目支出，提高资本配置效率。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 自由现金流 | 稳健 |\n| 资本配置 | 效率提升 |",
    },
    {
        "company": "腾讯控股",
        "year": "2024",
        "modality": "image",
        "content": "腾讯控股披露监管政策、游戏版号、数据安全和云服务竞争风险。公司通过合规审查和技术安全体系降低平台运营不确定性。",
        "raw_ref": "reports/2024/腾讯控股/fake-report-16-risk-map.png",
    },
    {
        "company": "隆基绿能",
        "year": "2024",
        "modality": "text",
        "content": "隆基绿能研发聚焦高效电池技术、硅片工艺和光伏组件可靠性。公司推进HPBC和其他新型电池路线，以提升转换效率和产品竞争力。",
        "raw_ref": "reports/2024/隆基绿能/annual-report.md#fake-report-17",
    },
    {
        "company": "隆基绿能",
        "year": "2024",
        "modality": "table",
        "content": "隆基绿能组件出货规模扩大，但光伏产业链价格下行压制营收弹性。海外市场需求增长，分布式项目和大型电站客户贡献订单。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 组件出货 | 规模扩大 |\n| 产业链价格 | 下行 |",
    },
    {
        "company": "隆基绿能",
        "year": "2024",
        "modality": "table",
        "content": "隆基绿能经营活动现金流承压，主要因为组件价格下降、客户账期拉长和库存去化。公司减少非必要资本开支，提升回款管理力度。",
        "raw_ref": "| 指标 | 2024表现 |\n| --- | --- |\n| 经营活动现金流 | 承压 |\n| 回款管理 | 力度提升 |",
    },
    {
        "company": "隆基绿能",
        "year": "2024",
        "modality": "image",
        "content": "隆基绿能面临光伏行业产能过剩、硅料价格波动、海外贸易政策和技术路线迭代风险。公司通过研发和全球渠道分散经营压力。",
        "raw_ref": "reports/2024/隆基绿能/fake-report-20-risk-map.png",
    },
]


def stable_index(text: str) -> int:
    digest = hashlib.sha256(text.encode("utf-8")).digest()
    return int.from_bytes(digest[:4], "big") % EMBED_DIM


def add_feature(vector: list[float], key: str, weight: float) -> None:
    vector[stable_index(key)] += weight


def iter_char_ngrams(text: str, n: int = 2) -> list[str]:
    compact = "".join(ch for ch in text if not ch.isspace())
    return [compact[i : i + n] for i in range(max(0, len(compact) - n + 1))]


def embed_text(text: str) -> list[float]:
    vector = [0.0] * EMBED_DIM

    for company in COMPANIES:
        if company in text:
            add_feature(vector, f"company:{company}", 1.2)

    for group, keywords in FEATURE_GROUPS.items():
        matched = False
        for keyword in keywords:
            if keyword in text:
                add_feature(vector, f"kw:{keyword}", 1.0)
                matched = True
        if matched:
            add_feature(vector, f"topic:{group}", 2.0)

    for gram in iter_char_ngrams(text):
        add_feature(vector, f"gram:{gram}", 0.03)

    norm = math.sqrt(sum(value * value for value in vector))
    if norm == 0:
        return vector
    return [value / norm for value in vector]


def build_records() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []

    for index, item in enumerate(DOCS, start=1):
        content = item["content"]
        records.append(
            {
                "doc_id": f"fake-report-{index:02d}",
                "content": content,
                "raw_ref": item["raw_ref"],
                "modality": item["modality"],
                "company": item["company"],
                "year": item["year"],
                DENSE_FIELD: embed_text(content),
            }
        )

    return records


def remove_existing_db() -> None:
    for path in ROOT_DIR.glob(f"{DB_PATH.name}*"):
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()


def reset_collection() -> MilvusClient:
    remove_existing_db()
    client = MilvusClient(uri=str(DB_PATH))

    schema = MilvusClient.create_schema(auto_id=False, enable_dynamic_field=False)
    schema.add_field(field_name="doc_id", datatype=DataType.VARCHAR, is_primary=True, max_length=64)
    schema.add_field(
        field_name="content",
        datatype=DataType.VARCHAR,
        max_length=4096,
        enable_analyzer=True,
        analyzer_params={"tokenizer": "jieba"},
    )
    schema.add_field(field_name="raw_ref", datatype=DataType.VARCHAR, max_length=4096)
    schema.add_field(field_name="modality", datatype=DataType.VARCHAR, max_length=16)
    schema.add_field(field_name="company", datatype=DataType.VARCHAR, max_length=64)
    schema.add_field(field_name="year", datatype=DataType.VARCHAR, max_length=8)
    schema.add_field(field_name=DENSE_FIELD, datatype=DataType.FLOAT_VECTOR, dim=EMBED_DIM)
    schema.add_field(field_name=SPARSE_FIELD, datatype=DataType.SPARSE_FLOAT_VECTOR)

    schema.add_function(
        Function(
            name="content_bm25",
            input_field_names=["content"],
            output_field_names=[SPARSE_FIELD],
            function_type=FunctionType.BM25,
        )
    )

    index_params = MilvusClient.prepare_index_params()
    index_params.add_index(
        field_name=DENSE_FIELD,
        index_name="dense_index",
        index_type="AUTOINDEX",
        metric_type="COSINE",
    )
    index_params.add_index(
        field_name=SPARSE_FIELD,
        index_name="sparse_bm25_index",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
        params={"inverted_index_algo": "DAAT_MAXSCORE", "bm25_k1": 1.2, "bm25_b": 0.75},
    )

    client.create_collection(
        collection_name=COLLECTION_NAME,
        schema=schema,
        index_params=index_params,
    )
    client.insert(collection_name=COLLECTION_NAME, data=build_records())
    client.flush(collection_name=COLLECTION_NAME)
    client.load_collection(collection_name=COLLECTION_NAME)
    return client


def get_collection_count(client: MilvusClient) -> int:
    try:
        stats = client.get_collection_stats(collection_name=COLLECTION_NAME)
        return int(stats.get("row_count", 0))
    except Exception:
        rows = client.query(
            collection_name=COLLECTION_NAME,
            filter='doc_id != ""',
            output_fields=["doc_id"],
            limit=1000,
        )
        return len(rows)


def dense_search_collection(
    client: MilvusClient,
    text: str,
    limit: int = 5,
    filter_expr: str | None = None,
) -> list[Any]:
    result = client.search(
        collection_name=COLLECTION_NAME,
        data=[embed_text(text)],
        anns_field=DENSE_FIELD,
        search_params={"metric_type": "COSINE", "params": {}},
        limit=limit,
        filter=filter_expr,
        output_fields=OUTPUT_FIELDS,
    )
    return list(result[0]) if result else []


def sparse_search_collection(
    client: MilvusClient,
    text: str,
    limit: int = 5,
    filter_expr: str | None = None,
) -> list[Any]:
    result = client.search(
        collection_name=COLLECTION_NAME,
        data=[text],
        anns_field=SPARSE_FIELD,
        search_params={"params": {}},
        limit=limit,
        filter=filter_expr,
        output_fields=OUTPUT_FIELDS,
    )
    return list(result[0]) if result else []


def hybrid_search_collection(
    client: MilvusClient,
    text: str,
    limit: int = 5,
    filter_expr: str | None = None,
) -> list[Any]:
    reqs = [
        AnnSearchRequest(
            data=[embed_text(text)],
            anns_field=DENSE_FIELD,
            param={"metric_type": "COSINE", "params": {}},
            limit=limit,
            filter=filter_expr,
        ),
        AnnSearchRequest(
            data=[text],
            anns_field=SPARSE_FIELD,
            param={},
            limit=limit,
            filter=filter_expr,
        ),
    ]
    result = client.hybrid_search(
        collection_name=COLLECTION_NAME,
        reqs=reqs,
        ranker=RRFRanker(k=60),
        limit=limit,
        output_fields=OUTPUT_FIELDS,
    )
    return list(result[0]) if result else []


def hit_value(hit: Any, key: str, default: Any = None) -> Any:
    if isinstance(hit, dict):
        return hit.get(key, default)
    if hasattr(hit, key):
        return getattr(hit, key)
    if hasattr(hit, "get"):
        try:
            return hit.get(key, default)
        except TypeError:
            return hit.get(key)
    return default


def hit_entity(hit: Any) -> dict[str, Any]:
    entity = hit_value(hit, "entity", {})
    if isinstance(entity, dict):
        return entity
    if hasattr(entity, "to_dict"):
        return entity.to_dict()
    return dict(entity) if entity else {}


def get_rows(hits: list[Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    for hit in hits:
        entity = hit_entity(hit)
        score = hit_value(hit, "distance")
        if score is None:
            score = hit_value(hit, "score")
        rows.append(
            {
                "id": entity.get("doc_id") or hit_value(hit, "id"),
                "content": entity.get("content", ""),
                "raw_ref": entity.get("raw_ref", ""),
                "modality": entity.get("modality", ""),
                "company": entity.get("company", ""),
                "year": entity.get("year", ""),
                "score": float(score) if score is not None else 0.0,
            }
        )

    return rows


def print_results(title: str, query: str, hits: list[Any]) -> list[dict[str, Any]]:
    rows = get_rows(hits)
    print(f"\n{'=' * 80}")
    print(title)
    print(f"Query: {query}")
    print(f"Result count: {len(rows)}")
    print("-" * 80)

    if not rows:
        print("No results")
        return rows

    for rank, row in enumerate(rows, start=1):
        print(
            f"#{rank} score={row['score']:.4f} modality={row['modality']} "
            f"company={row['company']} year={row['year']} doc_id={row['id']}"
        )
        print(f"   content: {row['content'][:110]}")
        print(f"   raw_ref: {row['raw_ref'][:110]}")

    return rows


def print_conclusion(
    dense_rows: list[dict[str, Any]],
    sparse_rows: list[dict[str, Any]],
    hybrid_rows: list[dict[str, Any]],
    company_hybrid_rows: list[dict[str, Any]],
    table_hybrid_rows: list[dict[str, Any]],
) -> None:
    hybrid_companies = sorted({row["company"] for row in hybrid_rows})
    company_filter_ok = bool(company_hybrid_rows) and all(
        row["company"] == "宁德时代" for row in company_hybrid_rows
    )
    table_filter_ok = bool(table_hybrid_rows) and all(
        row["modality"] == "table" for row in table_hybrid_rows
    )
    company_table_ok = bool(table_hybrid_rows) and all(
        row["company"] == "宁德时代" and row["modality"] == "table" for row in table_hybrid_rows
    )
    cashflow_top_ok = bool(table_hybrid_rows) and "现金流" in table_hybrid_rows[0]["content"]
    false_positive = [row["company"] for row in company_hybrid_rows if row["company"] != "宁德时代"]

    print(f"\n{'=' * 80}")
    print("Quick conclusion")
    print(f"- Milvus Lite DB path: {DB_PATH}")
    print(f"- Inserted records: {len(DOCS)}")
    print(f"- Dense search returned records: {len(dense_rows)}")
    print(f"- Sparse BM25 search returned records: {len(sparse_rows)}")
    print(f"- Hybrid query returned companies: {', '.join(hybrid_companies)}")
    print(f"- Hybrid company filter only returned 宁德时代: {company_filter_ok}")
    print(f"- Hybrid modality=table filter only returned tables: {table_filter_ok}")
    print(f"- Hybrid company + table filters matched 宁德时代 table records: {company_table_ok}")
    print(f"- Hybrid cashflow table top result contains 现金流: {cashflow_top_ok}")
    if false_positive:
        print(f"- Obvious false positives under hybrid company filter: {false_positive}")
    else:
        print("- Obvious false positives under hybrid company filter: none")
    print(
        "- Note: dense is a deterministic smoke-test vector; sparse is generated by "
        "Milvus BM25 Function from content."
    )


def main() -> None:
    client = reset_collection()
    print(f"Created collection: {COLLECTION_NAME}")
    print(f"Collection count: {get_collection_count(client)}")

    global_query = "研发投入和新能源业务进展"
    cash_query = "宁德时代现金流和回款情况"
    company_query = "宁德时代研发投入和新能源电池技术"

    dense_rows = print_results(
        "1) Dense vector search without filters",
        global_query,
        dense_search_collection(client, global_query, limit=6),
    )
    sparse_rows = print_results(
        "2) Sparse BM25 search without filters",
        cash_query,
        sparse_search_collection(client, cash_query, limit=6),
    )
    hybrid_rows = print_results(
        "3) Hybrid dense + sparse search without filters",
        global_query,
        hybrid_search_collection(client, global_query, limit=6),
    )
    company_hybrid_rows = print_results(
        '4) Hybrid search with scalar filter: company == "宁德时代"',
        company_query,
        hybrid_search_collection(
            client,
            company_query,
            limit=4,
            filter_expr='company == "宁德时代"',
        ),
    )
    table_hybrid_rows = print_results(
        '5) Hybrid search with filters: company == "宁德时代" and modality == "table"',
        cash_query,
        hybrid_search_collection(
            client,
            cash_query,
            limit=4,
            filter_expr='company == "宁德时代" and modality == "table"',
        ),
    )

    print_conclusion(dense_rows, sparse_rows, hybrid_rows, company_hybrid_rows, table_hybrid_rows)
    client.close()


if __name__ == "__main__":
    main()
